# frozen_string_literal: true
AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Metrics/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 125

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/SubjectStub:
  Enabled: false

Documentation:
  Enabled: false

require: rubocop-rspec